---
- name: Install Docker on EC2 instance
  hosts: ubuntu_instance  # Reference to your EC2 instance from inventory file
  become: true  # Elevate privileges to root
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up Docker stable repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is started and enabled on boot
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group (to avoid using sudo with docker commands)
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker installed: {{ docker_version.stdout }}"
