---
- name: Install Grafana
  hosts: monitoring_server
  become: true

  tasks:
    - name: Add Grafana GPG key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: true
        state: started
