---
# Tasks to run SonarQube container
- name: Pull SonarQube Docker image
  docker_image:
    name: sonarqube
    source: pull

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube
    state: started
    restart_policy: always
    published_ports:
      - "9000:9000"
    volumes:
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions
    env:
      SONARQUBE_JDBC_URL: jdbc:postgresql://localhost:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar