apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supermario-game
  template:
    metadata:
      labels:
        app: supermario-game
    spec:
      containers:
      - name: supermario-game
        image: 631172387421.dkr.ecr.us-east-1.amazonaws.com/supermario-game:latest
        ports:
        - containerPort: 3000
