name: Test Self-Hosted Runner

# Workflow triggers
on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

# Define the job
jobs:
  test-runner:
    runs-on: [self-hosted, runner1]  # Specify self-hosted and the label for your runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print a test message
      - name: Verify runner is working
        run: echo "Runner is working correctly!"

      # Step 3: Check the system information
      - name: Print system information
        run: |
          echo "Current User: $(whoami)"
          echo "Operating System: $(uname -a)"
          echo "Current Directory: $(pwd)"

      # Step 4: Simulate some work (optional)
      - name: Simulate work
        run: sleep 10  # Sleep for 10 seconds to mimic a real job
