name: Check Environment

on: [push]

jobs:
  check-environment:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: List files in the working directory
      run: Get-ChildItem -Path ${{ github.workspace }} -Recurse
      shell: pwsh

    - name: Check environment
      run: .\check-environment.ps1
      shell: pwsh
      working-directory: ${{ github.workspace }}