name: Debug Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug environment
        run: |
          echo "Checking environment..."
          pwd
          ls -la
          echo "Checking Node.js..."
          node -v || echo "Node.js is not installed"
          npm -v || echo "npm is not installed"
          echo "Checking Docker..."
          docker --version || echo "Docker is not installed"
          echo "Checking disk space..."
          df -h || echo "Command not available"