name: Check Environment

on: [push]

jobs:
  check-environment:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check environment
      run: .\check-environment.ps1
      shell: pwsh