name: Deploy Super Mario Game to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'yes' to confirm Terraform destroy"
        required: true
  delete:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: supermario-game
      CLUSTER_NAME: super-mario-eks
      TERRAFORM_DIR: terraform-files

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws
          cat > $HOME/.aws/credentials << EOF
          [default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          
          cat > $HOME/.aws/config << EOF
          [default]
          region=${{ env.AWS_REGION }}
          output=json
          EOF
          
          # Verify AWS configuration
          aws sts get-caller-identity || exit 1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"  # Specify version to avoid any issues

      - name: Initialize Terraform
        run: |
          if [ ! -d "terraform-files" ]; then
            echo "Error: terraform-files directory not found!"
            ls -la
            exit 1
          fi
          cd terraform-files || exit 1
          terraform init || exit 1
          # Verify initialization
          if [ ! -d ".terraform" ]; then
            echo "Error: Terraform initialization failed!"
            exit 1
          fi

      - name: Destroy Terraform resources if requested
        if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
        run: |
          cd terraform-files || exit 1
          echo "Starting Terraform destroy..."
          terraform destroy -auto-approve || exit 1
          echo "Terraform destroy completed successfully"

      - name: Apply Terraform if not destroying
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }}
        run: |
          cd terraform-files || exit 1
          echo "Starting Terraform apply..."
          terraform apply -auto-approve || exit 1
          echo "Terraform apply completed successfully"
          # Verify EKS cluster creation
          aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} || exit 1

      - name: Configure ECR and build/push image
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }}
        run: |
          echo "Setting up ECR repository..."
          # Create ECR repository if it doesn't exist
          if ! aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }} >/dev/null 2>&1; then
            echo "Creating ECR repository..."
            aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }} || exit 1
          fi
          
          # Get ECR URI
          ECR_URI=$(aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --query 'repositories[0].repositoryUri' --output text)
          if [ -z "$ECR_URI" ]; then
            echo "Error: Failed to get ECR URI"
            exit 1
          fi
          
          # Verify Docker directory exists
          if [ ! -d "docker" ]; then
            echo "Error: docker directory not found!"
            ls -la
            exit 1
          fi
          
          # Build and push Docker image
          echo "Logging into ECR..."
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${ECR_URI} || exit 1
          
          echo "Building Docker image..."
          cd docker || exit 1
          docker build -t ${{ env.ECR_REPOSITORY }}:latest . || exit 1
          docker tag ${{ env.ECR_REPOSITORY }}:latest ${ECR_URI}:latest || exit 1
          
          echo "Pushing image to ECR..."
          docker push ${ECR_URI}:latest || exit 1
          echo "Docker image pushed successfully"

      - name: Deploy to Kubernetes
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }}
        run: |
          echo "Configuring kubectl..."
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }} || exit 1
          
          # Verify k8s directory exists
          if [ ! -d "k8s" ]; then
            echo "Error: k8s directory not found!"
            ls -la
            exit 1
          fi
          
          cd k8s || exit 1
          echo "Applying Kubernetes configurations..."
          kubectl apply -f k8s-deployment.yml || exit 1
          
          # Update the deployment with new image
          echo "Updating deployment with new image..."
          ECR_URI=$(aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --query 'repositories[0].repositoryUri' --output text)
          if [ -z "$ECR_URI" ]; then
            echo "Error: Failed to get ECR URI"
            exit 1
          fi
          
          kubectl set image deployment/supermario-game supermario-game=${ECR_URI}:latest || exit 1
          echo "Waiting for deployment to complete..."
          kubectl rollout status deployment/supermario-game --timeout=180s || exit 1
          
          echo "Getting service URL..."
          HOSTNAME=$(kubectl get svc supermario-service -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          if [ -z "$HOSTNAME" ]; then
            echo "Warning: Could not get service hostname"
          else
            echo "Service is available at: $HOSTNAME"
          fi